Add DotNetHowToAutoComplete sample solution
Azure-Samples/search-dotnet-getting-started pull request #27
Opened 2018-05-18 22:20 UTC by mhko

@brjohnstmsft, @Yahnoosh 

This is the dot net sample for autocomplete.

2018-05-18 22:43 UTC, bitsforthought requested changes
This sample is consistent with our other samples, but is it useful? Since this feature is going to be used for type-ahead, perhaps we should have a sample with more sophisticated UX than a console app?

@HeidiSteen what do you think?

2018-05-18 22:43 UTC, brjohnstmsft commented on DotNetHowToAutoComplete/DotNetHowToAutoComplete/packages.config
> +  <package id="Microsoft.Azure.Search.Common" version="5.0.0" targetFramework="net461" />
You'll need to reference version 6-preview in order for this to work. You can test it locally by running `Build-SeachPackages.ps1`, and then make sure to include the binaries/packages directory in your local azure-sdk-for-net repo in your NuGet package sources.

2018-05-18 23:18 UTC, HeidiSteen commented
Mike Carter said he was trying to figure out how to do a bigger sample/tutorial around this.  Have you talked to him?  He is targeting autocomplete, and I believe he is also planning on contrasting autocomplete with suggesters, maybe doing some kind of side-by-side demo not unlike this one (for analyzers) : http://alice.unearth.ai/

2018-05-19 00:20 UTC, bitsforthought commented
@HeidiSteen that's a good suggestion. Assuming Mike creates a more comprehensive article/sample around Autocomplete, do you think we should still publish this sample? Does it provide enough value in your opinion?

@mhko -- Can you please follow up with Mike?

2018-05-19 00:53 UTC, mhko commented
Thanks @HeidiSteen @brjohnstmsft! Mike did talk to me about creating a post that covers both suggest and autocomplete. I am unsure if he also plans to write a sample. Will follow up.

2018-06-11 17:03 UTC, brjohnstmsft commented
Closing this since we've decided to work on a sample that isn't just a console app.

2018-06-11 17:03 UTC, closed without merging