Updated one of the query examples to be slightly more interesting for the doc
Azure-Samples/search-dotnet-getting-started pull request #34
Opened 2019-06-20 01:38 UTC by mrcarter8

@brjohnstmsft @HeidiSteen

2019-06-23 01:58 UTC, bitsforthought approved these changes

2019-06-23 02:00 UTC, brjohnstmsft commented
@mrcarter8 Something doesn't seem right with this PR. It has commits going back a year, but when I review it, I only see one very small change.

Can you please try to re-apply all your changes to a new branch off of master, and then re-submit your PR? Maybe that way I can see all the other complex-types related changes here.

2019-06-23 02:01 UTC, bitsforthought requested changes
These changes look fine, but the PR itself looks strange due to the large number of commits that don't show up in the diffs.

2019-06-24 15:23 UTC, closed without merging

2019-06-24 15:40 UTC, mrcarter8 commented
Not sure what was going on there…I abandoned the other PR and started a new one that looks much cleaner: https://github.com/Azure-Samples/search-dotnet-getting-started/pull/35

From: Bruce Johnston <notifications@github.com>
Sent: Saturday, June 22, 2019 7:01 PM
To: Azure-Samples/search-dotnet-getting-started <search-dotnet-getting-started@noreply.github.com>
Cc: Mike Carter <mcarter@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure-Samples/search-dotnet-getting-started] Updated one of the query examples to be slightly more interesting for the doc (#34)


@brjohnstmsft requested changes on this pull request.

These changes look fine, but the PR itself looks strange due to the large number of commits that don't show up in the diffs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fsearch-dotnet-getting-started%2Fpull%2F34%3Femail_source%3Dnotifications%26email_token%3DAHBWUAUAQEOKMWJDG45LECLP33KOFA5CNFSM4HZOSHXKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4LDGUQ%23pullrequestreview-253113170&data=02%7C01%7Cmcarter%40microsoft.com%7C1f94b168814a43fb777808d6f77ea7b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636968520692234535&sdata=tnIMhT1fLXOr20P48rJkD41YM1AuRGvSC8gMY96M2YA%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHBWUAS2MLSGW36M3MECCWLP33KOFANCNFSM4HZOSHXA&data=02%7C01%7Cmcarter%40microsoft.com%7C1f94b168814a43fb777808d6f77ea7b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636968520692244529&sdata=vpjS9MvBT1DRP9GdWxIWuONPrf0e0BgAkFGv0cAGxaI%3D&reserved=0>.